config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  registerable: 'users/registrations'} 
  resources :line_items
  resources :carts
  resources :products

  # devise_scope :user do
  #   get 'users/sessions/history', :to => 'users/sessions#history', as: "history"
  # end
  #get "/check" => "users/registrations#checkout"


  get "/checkout", :to => "carts#checkout"
  put "/checkout", :to => "carts#confirm"
  patch "/checkout", :to => "carts#confirm"

  get '/search' , to: 'search#search'

  

  #resources :orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  root "home#index"
  #get 'users/registrations/checkout', to: 'registrations#checkout', as: checkout_user_registrations

  get "/register", :to => "devise/registrations#new"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
    def index
    end
    
  end
  

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Home', root_path, class: "navbar-brand" %>



   <% if user_signed_in? %>
      
         <li class="nav-item"  style="color:#fff">
        <%= link_to 'Sign Out',  destroy_user_session_path, data: { 'turbo-method': :delete }  ,class: "navbar-brand"  %>
        </li>

         <li class="nav-item"  style="color:#fff">
        <%= link_to 'Edit Profile',  edit_user_registration_path  ,class: "navbar-brand" %>
        </li>

         <%=@cart = Cart.find(session[:cart_id])%>
         <%= link_to 'Cart', cart_path(@cart), class: "navbar-brand" %> 

        <%=@user = current_user%>
        <%= link_to 'History', carts_path , class: "navbar-brand" %> 

        <div class= "container">
          <%= render  "home/search" %>
        </div>

        <%else%>
          <li class="nav-item" style="color:#fff">
        <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-brand" %>
        </li>
            <li class="nav-item"  style="color:#fff">
        <%= link_to 'Sign In', new_user_session_path  , class: "navbar-brand" %>
        </li>

    <%end%>
 
   
  </body>


    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      
    
  </div>
</nav>

app/views/home/_search.html.erb
<h1>Products Search</h1>

<%= form_with url: "/search" , method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= f.text_field :q %>
    <%= f.submit "Go", name: nil %>
  </p>
<% end %>

app/views/home/index.html.erb
<div>
<li class= "btn">
 <%= link_to "View Products", products_path %>       
</li>
 </div>