config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
  registerable: 'users/registrations'} 
  resources :line_items
  resources :carts
  resources :products

  # devise_scope :user do
  #   get 'users/sessions/history', :to => 'users/sessions#history', as: "history"
  # end
  #get "/check" => "users/registrations#checkout"


  get "/checkout", :to => "carts#checkout"
  put "/checkout", :to => "carts#confirm"
  patch "/checkout", :to => "carts#confirm"

  get '/search' , to: 'search#search'

  

  #resources :orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  root "home#index"
  #get 'users/registrations/checkout', to: 'registrations#checkout', as: checkout_user_registrations

  get "/register", :to => "devise/registrations#new"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user, optional: true
    accepts_nested_attributes_for :user
    before_update :update_order_status #:update_stock

    def add_product (product)
        current_item = line_items.find_by(product_id: product.id)

        if current_item
            current_item.increment(:quantity)
        else
            current_item = line_items.build(product_id: product.id)
        
        end

        current_item

    end




  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end


  def update_order_status
    if self.order_status == "pending"
      self.order_status = "ordered"
      self.line_items.each {|item|
      item.product.stock = item.product.stock - item.quantity
      item.product.save}
    else
      self.order_status = "cancelled"
      self.line_items.each {|item|
      item.product.stock = item.product.stock + item.quantity
      item.product.save} 
    end
    
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

#include CurrentCart
before_action :set_cart, only: %i[ show edit update destroy  confirm ]
before_action :update_order_status, only: %i[update]
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
   def new
  @cart = current_user.carts.build
  end

  # GET /carts/1/edit
  def edit
    @cart.user = current_user

  end

  # POST /carts or /carts.json
  def create

    @cart = current_user.cart.build(cart_params)
    @cart.user = current_user
    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
     respond_to do |format|
     if @cart.update(cart_params)
      if params[:order_status] == "ordered"
        mail = UsersMailer.confirmation_email(current_user.id)
        mail.deliver_later
        format.html { redirect_to products_path, notice: "Your order has been placed" }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { redirect_to carts_path, notice: "Your order has been cancelled" }
        format.json { render :show, status: :ok, location: @cart }
      end

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to products_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

#GET /checkout
  def checkout
  end


#PUT /checkout
def confirm

  respond_to do |format|
    if @cart.update(cart_params)

      format.html { redirect_to products_path, notice: "Your order was cancelled" }
      format.json { render :show, status: :ok, location: @cart }
    else
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @cart.errors, status: :unprocessable_entity }
    end
  end


end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit( :user_id, :order_status,:shipping_address, :billing_address)
    end


    def update_order_status
      if params[:order_status] == "pending"
        params[:order_status] = "ordered"
      else
        params[:order_status] = "cancelled"
      end
      
    end

   
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">


<% if cart.order_status != "pending"%>
<div class = "card">

  <p>
    <strong>Order Number</strong>
    <%= cart.id %>
  </p>
  <p>
    <strong>Order Status</strong>
    <%= cart.order_status %>
  </p>


<%= render (cart.line_items) %>
  <p>
    <strong>Total Price:</strong>
    <%= cart.total_price %>
  </p>

  <p>
    <strong>Shipping Address</strong>
    <%= cart.shipping_address %>
  </p>

    <p>
    <strong>Billing Address</strong>
    <%= cart.billing_address %>
  </p>

<%if cart.order_status == "ordered"%>

<%= form_with(model: cart) do |form| %>
<div>
    <%= form.hidden_field :user_id %>
  </div>

 <%= form.submit "Cancel Order" %>
<%end%>
<%end%>

 



</div>
<%end%>


</div>

app/views/carts/_checkout.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% if @cart.order_status == "pending" %>
  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.label :order_status, style: "display: inline" %>
   :  <%=  @cart.order_status %>
  </div>

  <div>
    <%= form.label :shipping_address, style: "display: block"  %>
    <%= form.text_field :shipping_address ,  required: true %>
  </div>



  <div>
    <%= form.label :billing_address, style: "display: block"  %>
    <%= form.text_field :billing_address ,  required: true %>
  </div>

<div>
  Tax : 5%
</div>
<div>
  Shipping Charges: 30.0
</div>

  <%if @cart.total_price > 30.0%>
  <div>
      Total: <%=@cart.total_price*1.05 + 30.0%>
  </div>
  <div>
    <%= form.submit "Check Out" %>
  </div>


  <%end%>

  <% end%>
<% end %>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "checkout", cart: @cart %>

<br>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Order History</h1>

<div id="carts">
  <% current_user.carts.each do |cart| %>


    <%= render cart %>


  <% end %>
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
  <%= link_to "Continue Shopping?", products_path %>

  <section class = "section">

  <%= render (@cart.line_items) %>


  Total: <%=@cart.total_price%>
  <%= button_to "Empty Cart", @cart, method: :delete %>

<%if @cart.total_price > 0%>
<% if user_signed_in?  %>

<%= link_to "Checkout" , edit_cart_path , notice: "Confirm your shipping address" %>
<%= flash[:notice] = "Confirm your shipping address" %>

<% else%>
 <%= link_to "Checkout" , new_user_session_path , notice: "You must sign in to continue" %>
 <%= flash[:notice] = "You must sign in to continue" %>

 <% end%>
 <%end%>

  </section>
</div>